 [platformio]
default_envs = esp1, esp2, native

[common_firmware]
platform = espressif32@6.12.0
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
upload_speed = 921600
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Werror=return-type
lib_ldf_mode = chain+

[env:esp1]
extends = common_firmware
build_flags =
    ${common_firmware.build_flags}
    -DROBOT_ESP1=1
build_src_filter =
    +<common/>
    +<esp1/>
    -<esp2/>

[env:esp2]
extends = common_firmware
build_flags =
    ${common_firmware.build_flags}
    -DROBOT_ESP2=1
build_src_filter =
    +<common/>
    -<esp1/>
    +<esp2/>

[env:native]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -std=c++17
    -Wall
    -Wextra
    -Werror=return-type
build_src_filter =
    +<common/>
    -<esp1/>
    -<esp2/>
